// Code generated by MockGen. DO NOT EDIT.
// Source: helpers/interface.go

// Package helpers is a generated GoMock package.
package helpers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHelperInterface is a mock of HelperInterface interface.
type MockHelperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHelperInterfaceMockRecorder
}

// MockHelperInterfaceMockRecorder is the mock recorder for MockHelperInterface.
type MockHelperInterfaceMockRecorder struct {
	mock *MockHelperInterface
}

// NewMockHelperInterface creates a new mock instance.
func NewMockHelperInterface(ctrl *gomock.Controller) *MockHelperInterface {
	mock := &MockHelperInterface{ctrl: ctrl}
	mock.recorder = &MockHelperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelperInterface) EXPECT() *MockHelperInterfaceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockHelperInterface) GenerateToken(userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockHelperInterfaceMockRecorder) GenerateToken(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockHelperInterface)(nil).GenerateToken), userID)
}

// ValidateJWT mocks base method.
func (m *MockHelperInterface) ValidateJWT(tokenString string) (*Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateJWT", tokenString)
	ret0, _ := ret[0].(*Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateJWT indicates an expected call of ValidateJWT.
func (mr *MockHelperInterfaceMockRecorder) ValidateJWT(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateJWT", reflect.TypeOf((*MockHelperInterface)(nil).ValidateJWT), tokenString)
}
